# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty


# Setup
title: 박수민 개인 블로그
tagline:
description: '열심히 하는 개발자'


paginate: 5

# Custom vars


github: https://parknnna.github.io/blog/
repo: https://parknnna.github.io/blog/
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  #- jemoji               # 주석처리
  - jekyll-include-cache  # 추가

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  #- jemoji                  # 주석처리
  - jekyll-include-cache  #추가
