# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty


# Setup
title: Parknnna blog
tagline: 'A Jekyll theme'
description: '열심히 하는 개발자'


paginate: 5

# Custom vars


github: https://github.com/parknnna
repo: https://github.com/parknnna

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  #- jemoji               # 주석처리
  - jekyll-include-cache  # 추가

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  #- jemoji                  # 주석처리
  - jekyll-include-cache  #추가
